services:
  postgres:
    image: postgres:16-alpine
    container_name: dbs-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbs_user
      - POSTGRES_PASSWORD=dbs_password
      - POSTGRES_DB=dbs_customer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dbs-network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: dbs-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dbs-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: dbs-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dbs-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: dbs-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - dbs-network

volumes:
  postgres_data:

networks:
  dbs-network:
    driver: bridge